name: Multiple Environment Test Suite

on:
  workflow_call:
  workflow_dispatch:

jobs:
  test-suite:
    strategy:
      matrix:
        python:
          - version: "3.8"
            toxenv: "py38"
    uses: ./.github/workflows/single-test-suite.yml
    with:
      python_version: ${{ matrix.python.version }}
      toxenv: ${{ matrix.python.toxenv }}
